export const list = `
    [
        {
            "FirstName": "kevin",
            "LastName": "Anderson",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Male"
        },
        {
            "FirstName": "James",
            "LastName": "Pater",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Male"
        },
        {
            "FirstName": "Lebron",
            "LastName": "James",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Male"
        },
        {
            "FirstName": "Jennifer",
            "LastName": "Anderson",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Female"
        },
        {
            "FirstName": "kevin3",
            "LastName": "Anderson",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Male"
        },
        {
            "FirstName": "kevin3",
            "LastName": "Anderson",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Male"
        },
        {
            "FirstName": "kevin3",
            "LastName": "Anderson",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Male"
        },
        {
            "FirstName": "kevin3",
            "LastName": "Anderson",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Male"
        },
        {
            "FirstName": "kevin3",
            "LastName": "Anderson",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Male"
        },
        {
            "FirstName": "kevin3",
            "LastName": "Anderson",
            "Title": "Programmer",
            "Dob": "11/05/1990",
            "Address": "123 Somewhere street",
            "City":"Tampa",
            "State": "FL",
            "Zip":"33615",
            "Occupation": "Software Consultant",
            "HomePhone": "4072672154",
            "CellPhone": "4072672154",
            "Email": "kevinanderson381@gmail.com",
            "Gender":"Male"
        }
    ]
    `;
